// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var FolderviewReactJs = require("../reactComponents/Folderview.react.js");

function make(title, folderItems, children) {
  return ReasonReact.wrapJsForReason(FolderviewReactJs.default, {
              title: title,
              folderItems: folderItems
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
