// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("NoteDescriptionViewRe");

var containerStyle = {
  borderBottom: "1px solid #dddddd",
  margin: "5px",
  padding: "5px"
};

var titleStyle = {
  color: "#999999",
  fontSize: "17px",
  margin: "10px"
};

var iconStyle = {
  color: "#999999",
  fontSize: "16px",
  marginRight: "10px"
};

var horizontalStyle = {
  display: "flex",
  alignItems: "center",
  flexDirection: "row",
  justifyContent: "flex-start"
};

var timeStampStyle = {
  color: "#aaaaaa",
  fontSize: "13px",
  margin: "4px"
};

function make(note, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          style: containerStyle
                        }, React.createElement("div", {
                              style: horizontalStyle
                            }, React.createElement("i", {
                                  className: "far fa-file-alt",
                                  style: iconStyle
                                }), React.createElement("p", {
                                  style: titleStyle
                                }, "Sample Title")), React.createElement("p", {
                              style: timeStampStyle
                            }, "Jun 10th, 2019"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.containerStyle = containerStyle;
exports.titleStyle = titleStyle;
exports.iconStyle = iconStyle;
exports.horizontalStyle = horizontalStyle;
exports.timeStampStyle = timeStampStyle;
exports.make = make;
/* component Not a pure module */
