// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ContextMenuReact = require("../reactComponents/ContextMenu.react");

function make(dispatch, menuId, suffix, children) {
  return ReasonReact.wrapJsForReason(ContextMenuReact.default, {
              menuId: menuId,
              dispatch: dispatch,
              suffix: suffix
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
