// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var FileTreeReactReactJs = require("../reactComponents/FileTreeReact.react.js");

function make(isOpen, children) {
  return ReasonReact.wrapJsForReason(FileTreeReactReactJs.default, {
              isOpen: isOpen
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
