// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_module = require("bs-platform/lib/js/caml_module.js");

var $$Error = /* module */[];

var Reference = Caml_module.init_mod([
      "Firebase.re",
      70,
      6
    ], [[
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]]);

var DataSnapshot = Caml_module.init_mod([
      "Firebase.re",
      85,
      6
    ], [[
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]]);

Caml_module.update_mod([[
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]], Reference, Reference);

Caml_module.update_mod([[
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]], DataSnapshot, DataSnapshot);

var OnDisconnect = /* module */[];

var ThenableReference = /* module */[];

var Query = /* module */[];

var Database = /* module */[
  /* Reference */Reference,
  /* DataSnapshot */DataSnapshot,
  /* OnDisconnect */OnDisconnect,
  /* ThenableReference */ThenableReference,
  /* Query */Query
];

var UploadTask = /* module */[];

var Reference$1 = /* module */[];

var Storage = /* module */[
  /* UploadTask */UploadTask,
  /* Reference */Reference$1
];

var User = /* module */[];

var $$Error$1 = /* module */[];

var AuthCredential = /* module */[];

var AdditionalUserInfo = /* module */[];

var UserCredential = /* module */[];

var Auth = /* module */[
  /* User */User,
  /* Error */$$Error$1,
  /* AuthCredential */AuthCredential,
  /* AdditionalUserInfo */AdditionalUserInfo,
  /* UserCredential */UserCredential
];

var App = /* module */[];

exports.$$Error = $$Error;
exports.Database = Database;
exports.Storage = Storage;
exports.Auth = Auth;
exports.App = App;
/* Reference Not a pure module */
