// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var loginWithDispatcher = (
  function(email, password) {
    var firebase = require("firebase/app");
    require("firebase/auth");
    firebase.auth().createUserWithEmailAndPassword(email, password).catch((error) => {

    });

  }

);

exports.loginWithDispatcher = loginWithDispatcher;
/* loginWithDispatcher Not a pure module */
