// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Editor$ReactTemplate = require("./Editor.bs.js");
var NoteListRe$ReactTemplate = require("./reasonComponents/NoteListRe.bs.js");
var ReactFiletree$ReactTemplate = require("./reasonBindings/ReactFiletree.bs.js");

var appStyle = {
  display: "flex",
  flexDirection: "row"
};

var editorContainerStyle = {
  padding: "45px"
};

var maple = ReasonReact.reducerComponent("Maple");

function make(_children) {
  return /* record */[
          /* debugName */maple[/* debugName */0],
          /* reactClassInternal */maple[/* reactClassInternal */1],
          /* handedOffState */maple[/* handedOffState */2],
          /* willReceiveProps */maple[/* willReceiveProps */3],
          /* didMount */maple[/* didMount */4],
          /* didUpdate */maple[/* didUpdate */5],
          /* willUnmount */maple[/* willUnmount */6],
          /* willUpdate */maple[/* willUpdate */7],
          /* shouldUpdate */maple[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          style: appStyle
                        }, ReasonReact.element(undefined, undefined, ReactFiletree$ReactTemplate.make(self[/* send */3], self[/* state */1][/* menuBarOpen */2], /* array */[])), ReasonReact.element(undefined, undefined, NoteListRe$ReactTemplate.make(self[/* send */3], self[/* state */1][/* notes */0], /* array */[])), React.createElement("div", {
                              style: editorContainerStyle
                            }, ReasonReact.element(undefined, undefined, Editor$ReactTemplate.make(undefined, "Write Anything...", undefined, undefined, /* array */[]))));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* notes : array */[],
                      /* isLoaded */false,
                      /* menuBarOpen */true
                    ];
            }),
          /* retainedProps */maple[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                var note_000 = /* id */action[0];
                var note_003 = /* timestamp */( Date.now() );
                var note = /* record */[
                  note_000,
                  /* title */"New Note",
                  /* body */"",
                  note_003
                ];
                console.log(state[/* notes */0]);
                return /* Update */Block.__(0, [/* record */[
                            /* notes */state[/* notes */0].concat(/* array */[note]),
                            /* isLoaded */state[/* isLoaded */1],
                            /* menuBarOpen */state[/* menuBarOpen */2]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* notes */state[/* notes */0],
                            /* isLoaded */state[/* isLoaded */1],
                            /* menuBarOpen */!state[/* menuBarOpen */2]
                          ]]);
              }
            }),
          /* jsElementWrapped */maple[/* jsElementWrapped */13]
        ];
}

exports.appStyle = appStyle;
exports.editorContainerStyle = editorContainerStyle;
exports.maple = maple;
exports.make = make;
/* maple Not a pure module */
