// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("FileTree");

var fileTreeStyle = {
  borderRight: "solid #898989 1px",
  marginRight: "20px",
  minHeight: "100vh",
  minWidth: "20vw",
  padding: "20px"
};

var titleStyle = {
  margin: "5px"
};

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          style: fileTreeStyle
                        }, React.createElement("p", {
                              style: titleStyle
                            }, "Notes"), React.createElement("hr", undefined));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.fileTreeStyle = fileTreeStyle;
exports.titleStyle = titleStyle;
exports.make = make;
/* component Not a pure module */
