// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function genRandomValue(min, max) {
  var diff = max - min | 0;
  return Math.random() * diff + min | 0;
}

function generateColor(param) {
  var colorSet = /* array */[
    "#5fcc82",
    "#24d8b4",
    "#4f30cc",
    "#e71d36",
    "#53b3cb",
    "#f15946",
    "#7999e0",
    "#a9efa5",
    "#ff8ea1"
  ];
  var index = genRandomValue(0, colorSet.length);
  return Caml_array.caml_array_get(colorSet, index);
}

function sendDeleteFolderMessage(dispatchFunc, messageId) {
  return Curry._1(dispatchFunc, /* DeleteBottomBarItem */Block.__(5, [messageId]));
}

function sendRenameFolderMessage(dispatchFunc, messageId) {
  return Curry._1(dispatchFunc, /* SetEditableBottomBarItem */Block.__(4, [messageId]));
}

function sendRenameNoteMessage(dispatchFunc, messageId) {
  return Curry._1(dispatchFunc, /* SetEditableNote */Block.__(11, [messageId]));
}

exports.genRandomValue = genRandomValue;
exports.generateColor = generateColor;
exports.sendDeleteFolderMessage = sendDeleteFolderMessage;
exports.sendRenameFolderMessage = sendRenameFolderMessage;
exports.sendRenameNoteMessage = sendRenameNoteMessage;
/* No side effect */
