// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function genRandomValue(min, max) {
  var diff = max - min | 0;
  return Math.random() * diff + min | 0;
}

function generateColor(param) {
  var colorSet = /* array */[
    "#f2a541",
    "#f3ca40",
    "#36f1cd",
    "#13c4a3",
    "#80ced7",
    "#9e1946",
    "#6df287",
    "#4ce0d2",
    "#ff8ea1"
  ];
  var index = genRandomValue(0, colorSet.length);
  return Caml_array.caml_array_get(colorSet, index);
}

function sendDeleteMessage(dispatchFunc, messageId) {
  return Curry._1(dispatchFunc, /* DeleteBottomBarItem */Block.__(0, [messageId]));
}

exports.genRandomValue = genRandomValue;
exports.generateColor = generateColor;
exports.sendDeleteMessage = sendDeleteMessage;
/* No side effect */
